// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-like/app/user/service/internal/biz"
	"go-like/app/user/service/internal/conf"
	"go-like/app/user/service/internal/data"
	"go-like/app/user/service/internal/server"
	"go-like/app/user/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	verifyCodeRepo := data.NewVerifyCodeRepo(dataData)
	authUseCase := biz.NewAuthUseCase(userRepo, verifyCodeRepo, logger)
	followerRepo := data.NewFollowerRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo, verifyCodeRepo, followerRepo, logger)
	userService := service.NewUserService(authUseCase, userUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, userService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
